name: "docker-build-push"
description: "build and push docker image"
inputs: 
  DOCKER_REPO:
     required: true
  DOCKER_REGISTRY: 
    required: true
  DOCKER_USER:
    required: false
    default: "builder"
  QEMU_SETUP:
    required: false
    default: "true"
  DOCKER_PASSWORD:
    required: true
outputs:
  images: 
    description: "tagged images"
    value: "${{ steps.set_outputs.outputs.IMAGES }}"
runs:
  using: "composite"
  steps:

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
      if: ${{ inputs.QEMU_SETUP == 'true' }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      if: ${{ inputs.QEMU_SETUP == 'true' }}
    

    - name: Login to registry
      uses: docker/login-action@v1 
      with:
        registry: ${{ inputs.DOCKER_REGISTRY }}
        username: ${{ inputs.DOCKER_USER }}
        password: ${{ inputs.DOCKER_PASSWORD }}

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: ${{ inputs.DOCKER_REGISTRY}}/${{ inputs.DOCKER_REPO }}
        flavor: |
          latest=true
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=sha

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: .
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}

    - name: set output
      id: set_outputs
      shell: bash
      run: |
        IMAGES="${{ steps.meta.outputs.tags }}"
        IMAGES="${IMAGES//'\n/'/' '}"
        IMAGES="${IMAGES//'\r/'/''}"
        echo "::set-output name=IMAGES::$IMAGES"

    - name: print tags
      shell: bash
      run: |
        echo ${{ steps.set_outputs.outputs.IMAGES }}